### ISSUE TITLE
Option to rename/delete RStudio server sessions

### ISSUE THREAD

**Issue by pat-s** [hrbrmstr/RSwitch#12]
Would be nice to have :)

**Comment by hrbrmstr** [comment]
Gotcha. I went for super-minimal UX for at least one of those.

![image](https://user-images.githubusercontent.com/509878/68704490-605b1980-055a-11ea-96aa-964b75a586a1.png)

"Delete Session" deletes the session from the menu (not just closes the window).

I figured it was quick to add a session back so didn't make a management panel for this but I think I'm going to have to give in to a few other requests and make a broader "preferences" pane. 

thx for using RSwitch and taking the time to file an issue!

**Comment by pat-s** [comment]
Just found the button - I must have been blind. Sorry for that 😅 

I was like trying to find a way via the prefs pane to rename/delete for minutes and did not look into the window itself 🤦‍♂ 

Works!
