### ISSUE TITLE
RStudio server: Error when plotting due to missing cairo lib reference

### ISSUE THREAD

**Issue by pat-s** [hrbrmstr/RSwitch#13]
The cairo lib on the server installation is loaded via an env module. 
When trying to plot something locally in the server instance fails with

```r
Error in RStudioGD() : 
  Shadow graphics device error: r error 4 (R code execution error)
In addition: There were 50 or more warnings (use warnings() to see the first 50)
> warnings()
Warning messages:
1: In grDevices:::png("/tmp/Rtmp5yeLfo/85146b1c20ed40ccbf64df2beb6c877b.png",  ... :
  unable to load shared object '/opt/spack/opt/spack/linux-centos7-x86_64/gcc-9.2.0/r-3.5.2-4syrmqv6iyv2fduikyzcthlcadhxchtj/rlib/R/library/grDevices/libs//cairo.so':
  /opt/spack/opt/spack/linux-centos7-x86_64/gcc-9.2.0/harfbuzz-2.3.1-ql6i63kghmmmt7chl7j4ftixd2drougi/lib/libharfbuzz.so.0: undefined symbol: FT_Done_MM_Var
2: In grDevices:::png("/tmp/Rtmp5yeLfo/85146b1c20ed40ccbf64df2beb6c877b.png",  ... :
```

Looks like a complicated one but maybe you have an idea?

Just for the record, on the server directly (via the browser interface) everything works smoothly.

**Comment by hrbrmstr** [comment]
hrm. lemme see if I can try to reproduce. (thx again for using & filing issues!)

**Comment by pat-s** [comment]
Turns out this is a local thing related to R 3.5.2. 

Somehow this R installation I have on the server has some troubles getting the right pointers to cairo and harfbuzz. Since it works for all other R versions and with Rswitch, I'll close here.

(even though I could swear that it first only did not work in Rswitch 😅).

My counter for false-positive issues here is really high. Sorry for that 😶
