### ISSUE TITLE
Switch R Version via cli?

### ISSUE THREAD

**Issue by pat-s** [hrbrmstr/RSwitch#15]
Hi Bob,

I noticed that R version switching is only working properly if I do it via Rswitch. 

Simply setting `R_HOME` has the effect that frameworks of different R versions get mixed up and cause segfaults (I was simply using an cli wrapper).

Is there a way to bind the switching options of Rswitch to a hotkey or show what's going on behind the scenes? I was shortly browsing the source here but could not find anything specific on the first look.

**Comment by hrbrmstr** [comment]
Strangely enough, I was thinking the same thing this week (I was deep in cli stuff and needed to switch R versions and thought "boy it'd be nice if I didn't have to write a separate bash script to do this").

I'm thinking abt having a shell script come along for the ride with RSwitch and then have a menu option for "Install/Remove RSwitch shell command" which I'd prbly name `rswitch` and make a symbolic link to the script that'll be in the app.

There are key bindings for installed R versions if the RSwitch menu happens to be displayed (but that's not exactly as easy as you're suggesting).

So wld a cli script that if you just type `rswitch` shows you what's installed (likely with a numeric prefix) and what's active then if you enter `rswitch 1` or `rswitch 3.6` it'll switch to it work?

**Comment by hrbrmstr** [comment]
I also started work on the other items recently and will hopefully have a new version out before end of March.

**Comment by pat-s** [comment]
> I'm thinking abt having a shell script come along for the ride with RSwitch and then have a menu option for "Install/Remove RSwitch shell command" which I'd prbly name rswitch and make a symbolic link to the script that'll be in the app.

👍 

> There are key bindings for installed R versions if the RSwitch menu happens to be displayed (but that's not exactly as easy as you're suggesting).

Jup but the way is too long to arrive there 😅 
Lately I'm switching often due to catching issues with R-devel in pkgs and have multiple terminals open with different R versions. 

> So wld a cli script that if you just type rswitch shows you what's installed (likely with a numeric prefix) and what's active then if you enter rswitch 1 or rswitch 3.6 it'll switch to it work?

Yes, I'd prefer `rswitch <rversion>` as using a single integer might confuse things. I would bind it to an alias like `r36 = rswitch 3.6 && radian` anyways in practice so I am not really having a strong opinion here.

**Comment by pat-s** [comment]
Hi Bob, just wanted to touch base - any ETA for this? :)

**Comment by hrbrmstr** [comment]
@pat-s 

Well, this took forever to get to and was so stupid simple to do I rly shld not have put it off (while it was painful to tweak the settings for notarization, it was not hard to embed a cmdline app).

If you download <https://rud.is/dl/RSwitch-1.7.0.app.zip> and install it, you can then do the following from a terminal prompt:

```bash
$ ln -s /Applications/RSwitch.app/Contents/Resources/rswitch-cmd /usr/local/bin
```

The command-line app has the following options:

```bash
$ rswitch --help
OVERVIEW: Switch R versions.

USAGE: r-switch [--list] [<rversion>]

ARGUMENTS:
  <rversion>              The R version to switch to.

OPTIONS:
  -l, --list              List R versions.
  --version               Show the version.
  -h, --help              Show help information.
```

Just entering `rswitch` by itself shows the installed versions, marking the current one with a `*`:

```bash
$ rswitch
3.6
4.0 *
```

If you try to switch to one that doesn't exist it yells (and has a non-0 exit status):

```bash
$ rswitch 4.1
R version 4.1 not found.
```

And silently changes the current one on success:

```bash
$ rswitch 3.6
$ rswitch
3.6 *
4.0
```

Pls give it a go when you get a chance. I'm going to try to release it this week after I update docs.

**Comment by bryanhanson** [comment]
Looks like you actually need to type `rswitch-cmd` at the command line (since that's what in the `ln` command).  I guess I can change it.

**Comment by hrbrmstr** [comment]
Aye, my bad. I've updated the previous comment with the proper `ln` statement.

**Comment by pat-s** [comment]
Thanks Bob! Works like a charm. 

I was wondering if it would make sense to have static r-release/r-devel aliases. I.e. instead of only using version numbers, these could always point to the current release/dev versions.

While this might be hard to detect for the current release, r-devel is marked as such and being able to do `rswitch rdev` (or similar terms for r-devel) could be neat.
