### ISSUE TITLE
RStudio server sessions copy/paste

### ISSUE THREAD

**Issue by danwwilson** [hrbrmstr/RSwitch#16]
I'm not sure if this is a wider occurrence or not, however I've just started to try out Rswitch and am loving the connect to RStudio server piece to free my browser.

I've come across an issue where it seems that copy and paste using ctrl-c / ctrl-v are a little flaky in the window that is launched. I can right click and copy but no method of pasting is working at present.

I'm just curious if it might be something in my setup or if this is a more widely experienced issue. 

It's a bit hard to do a reprex for, but let me know if there is any additional information I can share to help diagnose.

**Comment by danwwilson** [comment]
So further to this, I had two server sessions connected, and it seems that this is only an issue for the second server session. The copy/pasting works in the first session. For now I'm back to a single active server session, but think it would be amazing to be able to have multiple open through Rswitch.

**Comment by hrbrmstr** [comment]
#ty for kicking the tyres and taking the time to file an issue!

let me try to reproduce today. do you have the same issue with Cmd-C and Cmd-V?

**Comment by danwwilson** [comment]
Same issue with cmd-c / cmd-v

**Comment by hrbrmstr** [comment]
thx.

I just fired up one RSwitch-managed connection to one RStudio Server I have and another RSwitch-managed connection to another one and tried the copy/paste thing and it did work as expected (come to think of it, I recall doing this quite a bit for a project back in December).

Can you provide a bit more info abt the macOS version and the RStudio Server versions? (#tyia)

**Comment by danwwilson** [comment]
Apologies for the delay in response. 

Running on macOS Catalina (10.15.3) 2017 MBP 13 inch with Touch Bar.

The RStudio Servers are individual instances spun up in docker. Typical docker file would be https://github.com/danwwilson/segmentr_docker and then I'll have them exposed over different ports.

Example of how the servers are spun up:

`docker run --rm -d -v /home/<user>/.gitconfig:/etc/gitconfig -v /data:/data -v /home/<user>/.ssh:/home/rstudio/.ssh --env PASSWORD=<password> -p 8789:8787 --name rstudio_89 thedatacollective/segmentr:latest`

`docker run --rm -d -v /home/dwilson/.gitconfig:/etc/gitconfig -v /data:/data -v /home/dwilson/.ssh:/home/rstudio/.ssh --env PASSWORD=<password> -p 8790:8787 --name rstudio_90 thedatacollective/segmentr:latest`

I should also mention that because this is all contained to my local network I'm not using SSL certificates and as such everything is over HTTP rather than HTTPS.

So when I connect via RSwitch the url would be `http://<server ip>:8789` or `http://<server ip>:8790` for each of the above docker containers

**Comment by danwwilson** [comment]
So I have gone through the age old approach of turning it off and on again and after a reboot of the Mac I'm able to spin up different containers on a range of ports, and it seems that the copy and paste is content.

Closing the issue as a result.
