### ISSUE TITLE
Suggested improvement for the documentation

### ISSUE THREAD

**Issue by guiastrennec** [hrbrmstr/RSwitch#3]
First of all thank you so much for this new version of RSwitch it is a true gem for all R users on Mac 👍. I would like to make a suggestion to add a note in the documentation for users using the R (.pkg) installer. Currently the documentation says:

> (You can also use the .pkg versions if you prefer a clicky-installer wizard.)

However, as mentioned on the CRAN documentation [page](https://cran.rstudio.org/doc/manuals/R-admin.html#Multiple-versions):

> The installer will remove any previous version of the R framework which it finds installed 

So if one tries to successively install multiple R versions (e.g. 3.5.3 and 3.6.1 as shown below) from the .pkg, the previous version will no longer be accessible and be labelled incomplete:
![Screen Shot 2019-09-03 at 11 12 58](https://user-images.githubusercontent.com/7304883/64163338-5e315c00-ce41-11e9-9f0e-124ec499d867.png)

The CRAN documentation page mentions that:
> This can be avoided by using pkgutil --forget

So I ran `pkgutil --pkgs | grep org.r-project` in terminal to list out the R files, and then I used 
```
sudo pkgutil --forget org.r-project.R.el-capitan.fw.pkg
sudo pkgutil --forget org.r-project.x86_64.tcltk.x11 
sudo pkgutil --forget org.r-project.x86_64.texinfo 
sudo pkgutil --forget org.r-project.R.el-capitan.GUI.pkg
```
After this installing a new version did not impact the pre-existing one.

**Comment by hrbrmstr** [comment]
This is an incredibly helpful suggestion! #y!!

Tis live now: https://rud.is/rswitch/guide/

**Comment by guiastrennec** [comment]
@hrbrmstr thank you very much for the prompt implementation and the credit! Going one step further one could think about having a menu item in RSwitch running this "forget" script in the background. This may be helpful for folks who do not feel comfortable in terminal or with sudo.
